dist: trusty
sudo: required
language: java
jdk:
- oraclejdk8
git:
  depth: 3
cache:
  directories:
  - "$HOME/.m2"
services:
- postgresql
before_script:
- psql -c 'create database frameworkeventstore;' -U postgres
- psql -c 'create database frameworkviewstore;' -U postgres
- psql -c 'create database frameworkfilestore;' -U postgres
- psql -c 'create database frameworksystem;' -U postgres
- psql -c "CREATE USER framework WITH PASSWORD 'framework';" -U postgres
addons:
  postgresql: '9.5'
  sonarcloud:
    organization: cjscommonplatform
    token:
      secure: KqWUD6nqDomQi78/Lr5Nv3LuvPvSEQOsh2mEJfQPP2C2OfEozo8bVPzbEVsL9NvB5sOxcjp7o/4iLZ3X6kg2/aTShCSg74vqHJ3FWPTvwFA5TXptFeHGGrleaEsAeaD9GSgVf3wPjXTtmS42Q6OnLx/nA4ZreDXANczUbwWKyYW0nB0c49Hb53j6gOBzp64VizzggaWh8taWpFPWZCwAXgahY3mnOTftVOfdCh5Pyt3+2fdNZPedX+J4JnHa5yIfFgUFz108hkWVlt4vKnWXhXAPEjvqotEAKnNx45YihjOQQR6z8P7B4ntXqeW5DD3gEo6eTooB36Gi17+FqBLL+eKMd/v6qj/smgCDbrfJgrFSJH80DGTnetX87efzeAiMp7FVbwNetfjlzt85dMJTwwXmqikDvv0f3R70K9R8/mYrSGEVJbwx4paJK0P5buE3ABMGWa7hRWT2mZQs9tBmWrjdR/h0JmMA6Kop04jwxGgX5EAYtfWTLzhsGbtN1Q4FQ8mZkqnTIuVvsOfD7045Zxir9uhKjF0lJ8bIEGjMurbO9lp3ov+0KUHq2zrHU5Y+l9YKwC4jwR7ooUHuwdj5L9K8avhfRixT7Whxm0OngeCcmN+XxrGJy5qEqfHE1I6E7ewP9mwmppedEbJN13bH3b3L5VqW047rBDvrKeYdUHE=
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
- ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
- ln -sfT ${PWD}/target/travis-settings/mvnw mvnw
- ln -sft ${PWD} ${PWD}/target/travis-settings/.mvn
install: "${PWD}/target/travis-settings/java/install.sh -e -q -DexcludeGroupIds=uk.gov.justice.service,uk.gov.justice.services"
script: "${PWD}/target/travis-settings/java/script-install.sh coveralls:report sonar:sonar"
after_success: "${PWD}/target/travis-settings/java/after_success.sh"
notifications: 
env:
  global:
  - PGPORT=5432
  - secure: QMdzKRf/D2kMnXliJnieE6ojWmJVu+vaRUuHpw49/83KA08AjZh+27T7oUJIuYw1d44PQITNOeXQbHi80dhHj9dhVUJr0zsIHwXWKSzZARF44dqSJ9avl4Ov4pfgy2Y2iCAszLaErU+8WLcpf8pvWUpzEyhdIlrpx+yaIpPsek6vpDTatuyIQd8VpZ6VDPS/okhCXMBxgUWT76sSAUNLvBZjC2kLgCEI8zAJyrjl8RElFkOI6hMQe7GA6otYdkows93efgaQYziRrAVsfIQW2xnhcprAPDwNabqLGLqf73C9vBBBTCeIxU8dq+M4pNlXtuaI9hy6kbqevGoTeEnyOW3h94ZaEq0RkXtpAToobDKFSoO2yB9AHQFwsO4z0xoS8jPkoD1q/j1oxkXy9x6akbuD0HrQTwfNk5gI9/CmlBEL+X4nwRiBY/VmnIMjRstRIyUp9qBVaA7FthjGuocSl8Umx64VvuLDY7yR3o/Hd71HsHdv79xp66VYcX5f2jPcUVhcAZw9esOs0HDc8znGLeLb/HDy+hDz2RF4NcIZ+7rMUctlCjpaRKneCJHXADTr8hk+eFblBqHKGCy0ZP5b4I3+QXtrfFqGqI4GIXfRIAo6sg1fuBosC4FvmIgrRYVFwLASG0jPGPerqlMtPTHHo70TJY5qk52K/dxiu+tlcfM=
  - secure: X3nZxSFJWqSf7QqjUYarnpVGQKi+Owbc2gLhWsLb4EEYHGXPt5gGjNMbOk2YT8knwlraZDjUdgirA4CUg+6s/iS10nuzIRy6EFy2CbNoUBvo27QLquJEimVLdbuWhzgMJmrYAwAPFn3X5TV9/WK3no3vMSrllM/kiaiI6qo7oySFBVBpGCHuO15Qn2ZyLwe3ChHdGD1hbBvuEYZRaZpEh55Mv2lIs61fUqSP6KMu6r/z1YD8Az9S3krBWb0iq2HKGb7dn2kgIvz4+qjei4PHbj0eG4yFHzuFU1o3knlzQSGv79j9++0VX+/AYdkY4bldZ/IkdFJnWV1vdUIeC/a79Jo1o7ISXLG5Jwoq/aoOEADpoGMMCrKd3X23sMjJIj1th4vl53J6OOCy5PP12XqKDYhu/jia4BSP/AHRECxTb/af1MQf8E2BE9FWu01S1oMsqiJlQvsUpP6HsjzMj4y7kVYO2gTVH73nnXmINbWeJnrRNwRIOIVaa3pf/rX3L/fPr6TmJUWtnfDHadbfLa35HRANRb0+L/Dmth2WS8SIaClOOy/TkPNOs+UZgdINmUsKrerba/RR+kZ1F5XMnwu9xcBgem7sG1cQL1fHzhtOn2x8VLbxQZqEr/XBHVVQbGzVFMnbxZ+7sNYnaIqhC6RpJPE0Jf5h8bJz0GpMpGAZZ6k=
