dist: trusty
sudo: required
language: java
jdk:
- oraclejdk8
git:
  depth: 3
cache:
  directories:
  - "$HOME/.m2"
services:
- postgresql
before_script:
- psql -c 'create database frameworkeventstore;' -U postgres
- psql -c 'create database frameworkviewstore;' -U postgres
- psql -c 'create database frameworkfilestore;' -U postgres
- psql -c 'create database frameworksystem;' -U postgres
- psql -c 'create database fileservice;' -U postgres
- psql -c "CREATE USER framework WITH PASSWORD 'framework';" -U postgres
- psql -c "CREATE USER fileservice WITH PASSWORD 'fileservice';" -U postgres
addons:
  postgresql: '9.5'
  sonarcloud:
    organization: cjscommonplatform
    token:
      secure: KqWUD6nqDomQi78/Lr5Nv3LuvPvSEQOsh2mEJfQPP2C2OfEozo8bVPzbEVsL9NvB5sOxcjp7o/4iLZ3X6kg2/aTShCSg74vqHJ3FWPTvwFA5TXptFeHGGrleaEsAeaD9GSgVf3wPjXTtmS42Q6OnLx/nA4ZreDXANczUbwWKyYW0nB0c49Hb53j6gOBzp64VizzggaWh8taWpFPWZCwAXgahY3mnOTftVOfdCh5Pyt3+2fdNZPedX+J4JnHa5yIfFgUFz108hkWVlt4vKnWXhXAPEjvqotEAKnNx45YihjOQQR6z8P7B4ntXqeW5DD3gEo6eTooB36Gi17+FqBLL+eKMd/v6qj/smgCDbrfJgrFSJH80DGTnetX87efzeAiMp7FVbwNetfjlzt85dMJTwwXmqikDvv0f3R70K9R8/mYrSGEVJbwx4paJK0P5buE3ABMGWa7hRWT2mZQs9tBmWrjdR/h0JmMA6Kop04jwxGgX5EAYtfWTLzhsGbtN1Q4FQ8mZkqnTIuVvsOfD7045Zxir9uhKjF0lJ8bIEGjMurbO9lp3ov+0KUHq2zrHU5Y+l9YKwC4jwR7ooUHuwdj5L9K8avhfRixT7Whxm0OngeCcmN+XxrGJy5qEqfHE1I6E7ewP9mwmppedEbJN13bH3b3L5VqW047rBDvrKeYdUHE=
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
- ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
- ln -sfT ${PWD}/target/travis-settings/mvnw mvnw
- ln -sft ${PWD} ${PWD}/target/travis-settings/.mvn
install: "${PWD}/target/travis-settings/java/install.sh -e -q -DexcludeGroupIds=uk.gov.justice.service,uk.gov.justice.services"
script: "${PWD}/target/travis-settings/java/script-install.sh coveralls:report sonar:sonar"
after_success: "${PWD}/target/travis-settings/java/after_success.sh"
notifications: 
env:
  global:
  - PGPORT=5432
  - secure: JxixTy4AbobObx4GiIBOOlX0PYJt1b4zHbaLT1pEAh0h240R2EQOXBbb655oWzPI4Rhl28PAChifWi+8xiq7K07kXOz8kbyH2Z/i+5VkYFg9KrCFtSRPzgpoqLeSUS4ITyB8rGuSl0/1EZedT2b1jJ5RE4l7uRJ9yRubiupHUJRroPPjbNInk3hMyWtn6ITCLhf+8tU4C0y47LfHYKdQvB9lABZhJCa2iu9oWs3cWQfgtQ7aHoeySv5nL+qitgl6Y2rEQLCTKr1UMDgEP84zrcB/wvFzQ8ezNj7G5BbfZazabd8SIXp9eKfZj/1GZsPBCgSDGjedHsK1UsL92iltLS6janQc1HY6OyRQkEcgqYtYonW3fZjpot0S4EKFVI1144/ZifueoCTryRcK3oBLTQYQvRREyNJMDQoEdv99j4CCBIECVhv/WRSjgtFEsxPj442tkUblmHjk/CTiPd4D2x+roEQdx1AqCt9vd1vVkWgrtgsjSIaXZCcEQMQTv6M1Z8dcZQzOkFx6wM9UnySLvK5jcCJBv5OWlUPzdzzic3IVjmBBYHZAa1HDfsTEdQltneWY20A5PJBZNzE8dy959QKRkUH+YBDQcJ3HzM+kstI8o2xrZkcRPK0kP6pZD3tkWyFMDKJpeYtPgOYqEk9komzr9B73fhX3bR+ppGMUUbg=
  - secure: hTr5zSivQwKd3+BmbT2lrGjhgzYagc/nYW17vDE08ViDrCsxkIiZ4q0XWxhZcPcZjeuWmwJ9f1wAscsadFZvLu9n7lBaY2ULjD+fadPyyCW7Ux6yBCT5ShGoQeWnMpksx2jzHpnD6J0faKzQJgiawy9VXTD9n+Y/3eZxuL8auAp4ay3l/KZVqMCxGanQ9ioVAGD9/e5xW+ywBv7fdEIjJ7zYBQhU8TYt6hPwYpIBUCAGvBxuH6BZbhG+IKOEbh1Y7QHUZb6n02Q9KsE2nHZzKq2ub8MGMYSD2IPyqcTmXnBFz7fq5WLXiUkKmzat97l4eEliO4WGzhP4iXhHfmrMyjMgUumJ29uPwTYXIzyww/4A8cW8agWCMScV6aD8D8VI3srQUPBy7XRRRen6OD6jwTwJT/4mqCbDBuuZx3Ie7S09QvWecHhfy7AR9jURJoUPyVQd04KBzlP0sX8TovxGLaLi+zBBU8QGIzbdWYegnucHuBp9ATeOQMzQu33Iu8yMKtfLELQwG17AH5Aksi5qyopGVZcHx4B5/BAB4qeZ8ybCeq4PWh1UKw7KvTSIcKTMtg1fJA05ipmhDjH1uASDIJaiHSy8tWk6uIlZ+2I2+8Esa0Th6wKRRKe1A1PLNs/s9KSrFDkujCy/19fTXB6Kc5M/j2xMC+Y7SOKvLmlIV/A=
